# 대장균 개체의 ID, 자식 수 CHILD_COUNT

SELECT P.ID, IFNULL(C.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA P LEFT OUTER JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) C ON P.ID=C.PARENT_ID
ORDER BY P.ID ASC